// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import boundaries from 'eslint-plugin-boundaries';
import prettier from 'eslint-config-prettier';

/**
 * Layering rules are enforced here because this monorepo has no Nx to do it.
 * The dependency direction is one-way and is part of the template's contract:
 *
 *   apps/*          -> libs/*, packages/*
 *   libs/ui         -> libs/primitives, libs/i18n, packages/contracts
 *   libs/core       -> packages/contracts ONLY  (no UI, and never `environment`)
 *   libs/primitives -> nothing internal
 *   packages/db     -> packages/contracts
 *   packages/contracts -> nothing internal
 *
 * If you need to break one of these, the answer is almost always to move the
 * shared thing into packages/contracts, not to relax the rule.
 */
const ELEMENTS = [
  { type: 'app-api', pattern: 'apps/api' },
  { type: 'app-web', pattern: 'apps/web' },
  { type: 'app-dashboard', pattern: 'apps/app' },
  { type: 'lib-core', pattern: 'libs/core' },
  { type: 'lib-ui', pattern: 'libs/ui' },
  { type: 'lib-primitives', pattern: 'libs/primitives' },
  { type: 'lib-i18n', pattern: 'libs/i18n' },
  { type: 'pkg-contracts', pattern: 'packages/contracts' },
  { type: 'pkg-db', pattern: 'packages/db' },
];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/.angular/**',
      'packages/db/migrations/**',
      // Generated by `npx auth generate` — reviewed on every upgrade, never linted.
      'packages/db/src/schema/auth.schema.ts',
      'infra/**',
      'docs/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,mts,cts}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Use a `const` object + union type instead of an enum (see CLAUDE.md).',
        },
      ],
    },
  },

  {
    files: ['**/*.{ts,mts,cts,js,mjs}'],
    plugins: { boundaries },
    settings: {
      'boundaries/elements': ELEMENTS,
      'boundaries/include': ['apps/**', 'libs/**', 'packages/**'],
      // Required: boundaries resolves imports through the standard resolver settings.
      // Without the TypeScript resolver the `@app/*` aliases resolve to nothing and
      // every layering policy silently passes.
      'import/resolver': {
        typescript: { alwaysTryTypes: true, project: ['tsconfig.base.json'] },
      },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          policies: [
            {
              from: { element: { type: 'app-api' } },
              allow: [
                { to: { element: { type: 'pkg-contracts' } } },
                { to: { element: { type: 'pkg-db' } } },
              ],
            },
            {
              from: { element: { type: 'app-web' } },
              allow: [
                { to: { element: { type: 'lib-*' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'app-dashboard' } },
              allow: [
                { to: { element: { type: 'lib-*' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'lib-ui' } },
              allow: [
                { to: { element: { type: 'lib-primitives' } } },
                { to: { element: { type: 'lib-i18n' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'lib-core' } },
              allow: [{ to: { element: { type: 'pkg-contracts' } } }],
            },
            { from: { element: { type: 'lib-primitives' } }, allow: [] },
            { from: { element: { type: 'lib-i18n' } }, allow: [] },
            {
              from: { element: { type: 'pkg-db' } },
              allow: [{ to: { element: { type: 'pkg-contracts' } } }],
            },
            { from: { element: { type: 'pkg-contracts' } }, allow: [] },
          ],
        },
      ],
    },
  },

  {
    // libs/core must stay environment-agnostic: it receives its configuration through
    // provideCore(), so the same library works in apps/web and apps/app unchanged.
    files: ['libs/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/environment', '**/environment.*', '**/environments/*'],
              message:
                'libs/core must not read environment.*. Pass configuration in via provideCore().',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['**/*.spec.ts', '**/*.e2e-spec.ts', 'scripts/**/*.mjs'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
    },
  },

  prettier,
);
