// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import boundaries from 'eslint-plugin-boundaries';
import globals from 'globals';
import prettier from 'eslint-config-prettier';

/**
 * Layering rules are enforced here because this monorepo has no Nx to do it.
 * The dependency direction is one-way and is part of the template's contract:
 *
 *   apps/app        -> libs/*, packages/contracts
 *   apps/web        -> libs/core, libs/ui, libs/i18n, libs/primitives, contracts
 *                      (NOT libs/admin: the marketing site has no back office)
 *   libs/admin      -> libs/core, libs/ui, libs/i18n, libs/primitives, contracts
 *   libs/ui         -> libs/primitives, libs/i18n, packages/contracts
 *   libs/core       -> packages/contracts ONLY  (no UI, and never `environment`)
 *   libs/primitives -> nothing internal
 *   packages/db     -> packages/contracts
 *   packages/contracts -> nothing internal
 *
 * If you need to break one of these, the answer is almost always to move the
 * shared thing into packages/contracts, not to relax the rule.
 */
const ELEMENTS = [
  { type: 'app-api', pattern: 'apps/api' },
  { type: 'app-web', pattern: 'apps/web' },
  { type: 'app-dashboard', pattern: 'apps/app' },
  { type: 'lib-core', pattern: 'libs/core' },
  /**
   * The platform's back office, kept out of the tenant's product on purpose.
   *
   * It is the largest single area of the dashboard and the one almost nobody sees, so
   * the direction of the dependency is what keeps it from seeping: the app may load it
   * lazily, and it may use the shared libraries — but no tenant screen can import from
   * it, and it can import nothing of the tenant's. Without that rule the separation is
   * a folder name.
   *
   * It stays a library rather than becoming apps/admin for now: the split is a
   * deployment decision (see CLAUDE.md), and with this boundary in place making it one
   * is moving a folder and adding a build target.
   */
  { type: 'lib-admin', pattern: 'libs/admin' },
  { type: 'lib-ui', pattern: 'libs/ui' },
  { type: 'lib-primitives', pattern: 'libs/primitives' },
  { type: 'lib-i18n', pattern: 'libs/i18n' },
  { type: 'pkg-contracts', pattern: 'packages/contracts' },
  { type: 'pkg-db', pattern: 'packages/db' },
];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/.angular/**',
      'packages/db/migrations/**',
      // Generated by `npx auth generate` — reviewed on every upgrade, never linted.
      'packages/db/src/schema/auth.schema.ts',
      // Vendored spartan components: copied in by `ng g @spartan-ng/cli:ui` and
      // overwritten on every regeneration, so linting them means re-fixing the same
      // findings forever. They are reviewed as a diff when added or updated.
      'libs/primitives/**',
      // Compiled output must never be linted. It should not exist outside dist/ either —
      // `noEmitOnError` in tsconfig.base.json stops a failed build from scattering it.
      '**/*.js.map',
      '**/*.d.ts',
      'infra/**',
      'docs/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,mts,cts}'],
    rules: {
      // TypeScript already resolves identifiers; `no-undef` only produces false
      // positives on type-only names. This is the typescript-eslint recommendation.
      'no-undef': 'off',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Use a `const` object + union type instead of an enum (see CLAUDE.md).',
        },
      ],
    },
  },

  {
    files: ['**/*.{ts,mts,cts,js,mjs}'],
    plugins: { boundaries },
    settings: {
      'boundaries/elements': ELEMENTS,
      'boundaries/include': ['apps/**', 'libs/**', 'packages/**'],
      /**
       * How `@app/*` imports get classified — and it is load-bearing.
       *
       * The plugin resolves every import through eslint-module-utils, which reads
       * this setting. When it cannot resolve one, the dependency is described as an
       * EXTERNAL module and no policy applies to it: the import is not refused, it is
       * invisible. That is the failure mode to fear here, because the rules keep
       * passing.
       *
       * `tsconfig.json` ALONE, and that is the fix rather than an omission: it is the
       * only one carrying the `@app/*` paths, and passing it together with
       * `tsconfig.base.json` makes the resolver answer "not found" for every alias.
       * Verified by calling the resolver directly, after a deliberately forbidden
       * aliased import went through without a word.
       *
       * The backend aliases need nothing here: `@app/contracts` and `@app/db` are real
       * workspace packages and resolve as packages.
       *
       * If you add a path to tsconfig.json, write a forbidden import that uses it and
       * watch the rule fail. `boundaries/debug` prints what the plugin made of a
       * dependency when it does not.
       */
      'import/resolver': {
        typescript: { alwaysTryTypes: true, project: ['tsconfig.json'] },
      },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          policies: [
            {
              from: { element: { type: 'app-api' } },
              allow: [
                { to: { element: { type: 'pkg-contracts' } } },
                { to: { element: { type: 'pkg-db' } } },
              ],
            },
            {
              // Explicit rather than `lib-*`: the marketing site must never be able to
              // pull in the platform's back office.
              from: { element: { type: 'app-web' } },
              allow: [
                { to: { element: { type: 'lib-core' } } },
                { to: { element: { type: 'lib-ui' } } },
                { to: { element: { type: 'lib-i18n' } } },
                { to: { element: { type: 'lib-primitives' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'app-dashboard' } },
              allow: [
                { to: { element: { type: 'lib-*' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            /**
             * ...with one exception: no tenant screen may import the back office.
             *
             * `lib-*` above would otherwise allow it, and the whole point of moving
             * the administration area out of `features/` was to stop it seeping back
             * in one convenient import at a time.
             *
             * These two rules are last-write-wins, so the narrower one comes second:
             * the route table is the single legitimate door, because the router has to
             * name the chunks it lazy-loads. Everything else is refused.
             */
            {
              from: { element: { type: 'app-dashboard' } },
              disallow: { to: { element: { type: 'lib-admin' } } },
            },
            {
              from: { file: { path: '**/app.routes.ts' } },
              allow: { to: { element: { type: 'lib-admin' } } },
            },
            {
              /**
               * Administration screens are built from the same shared pieces as every
               * other screen — which is the evidence that they needed a boundary and
               * not a rewrite. What they may not do is reach back into an application.
               */
              from: { element: { type: 'lib-admin' } },
              allow: [
                { to: { element: { type: 'lib-core' } } },
                { to: { element: { type: 'lib-ui' } } },
                { to: { element: { type: 'lib-i18n' } } },
                { to: { element: { type: 'lib-primitives' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'lib-ui' } },
              allow: [
                { to: { element: { type: 'lib-primitives' } } },
                { to: { element: { type: 'lib-i18n' } } },
                { to: { element: { type: 'pkg-contracts' } } },
              ],
            },
            {
              from: { element: { type: 'lib-core' } },
              allow: [{ to: { element: { type: 'pkg-contracts' } } }],
            },
            { from: { element: { type: 'lib-primitives' } }, allow: [] },
            {
              // Calendar localisation has to reference the spartan date-picker token
              // it configures; there is no way to express it without the primitive.
              from: { element: { type: 'lib-i18n' } },
              allow: [{ to: { element: { type: 'lib-primitives' } } }],
            },
            {
              from: { element: { type: 'pkg-db' } },
              allow: [{ to: { element: { type: 'pkg-contracts' } } }],
            },
            { from: { element: { type: 'pkg-contracts' } }, allow: [] },
          ],
        },
      ],
    },
  },

  {
    /**
     * NestJS resolves constructor dependencies through `emitDecoratorMetadata`, so a
     * service that only ever appears in a type position is still needed at runtime.
     * `consistent-type-imports` cannot see that: its autofix rewrites those imports to
     * `import type`, the import vanishes from the emitted JS, the metadata becomes
     * `Object`, and dependency injection fails at runtime with an error that points
     * nowhere near the import. The rule stays on everywhere else.
     */
    files: ['apps/api/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },

  {
    // libs/core must stay environment-agnostic: it receives its configuration through
    // provideCore(), so the same library works in apps/web and apps/app unchanged.
    files: ['libs/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/environment', '**/environment.*', '**/environments/*'],
              message:
                'libs/core must not read environment.*. Pass configuration in via provideCore().',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['scripts/**/*.mjs', '**/scripts/**/*.mjs', '*.mjs'],
    languageOptions: { globals: globals.node },
  },

  {
    files: ['**/*.spec.ts', '**/*.e2e-spec.ts', '**/scripts/**/*.mjs'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
    },
  },

  prettier,
);
