/**
 * Drizzle schema barrel.
 *
 * Two halves, and the distinction matters:
 *   - `auth.schema.ts` is GENERATED by `npx auth generate`. Never hand-edit it; it is
 *     regenerated on every Better Auth upgrade and reviewed like any other diff.
 *   - `app/*.ts` is ours.
 *
 * drizzle-kit reads this file, so anything not exported here does not exist as far as
 * migrations are concerned.
 */
export * from './_helpers';

export * from './app/plan';
export * from './app/stripe-event';
export * from './app/feature-flag';
export * from './app/app-setting';
